# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-true-edgeai"
BBFILE_PATTERN_meta-true-edgeai = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-true-edgeai = "6"

LAYERDEPENDS_meta-true-edgeai = "core"
LAYERSERIES_COMPAT_meta-true-edgeai = "scarthgap"
